### ISSUE TITLE
Mixed up labels in the inference notebook and on huggingface model card?

### ISSUE THREAD

**Issue by aaalexlit** [amandakonet/climate-change-misinformation#2]
@amandakonet, I think in the inference notebook the 'contradiction' and 'entailment' labels are in incorrect order, can it be?
<img width="682" alt="image" src="https://user-images.githubusercontent.com/116374290/220446510-d213231c-fcce-458c-9040-2b1f9826e469.png">
And as a consequence the same happens to the huggingface model card https://huggingface.co/amandakonet/climatebert-fact-checking
The original dataset has `{'SUPPORTS':0, 'REFUTES':1, 'NOT_ENOUGH_INFO':2}` mapping
and for training you seem to use the same mapping
<img width="797" alt="image" src="https://user-images.githubusercontent.com/116374290/220447424-6460213c-ae6d-4178-829f-d0cf3e2006f7.png">

**Comment by amandakonet** [comment]
Hi @aaalexlit,

Looks like I did switch the order... I will update the inference notebook and the model card. Thanks for catching this!
